[workspace]

members = [
  "services/access_control/enclave",
  "services/authentication/enclave",
  "services/storage/enclave",
  "services/execution/enclave",
  "services/frontend/enclave",
  "services/management/enclave",
  "services/scheduler/enclave",
  "tests/unit/enclave",
  "tests/functional/enclave",
  "tests/integration/enclave",
  "tool/enclave",
]

exclude = [
]

[patch.crates-io]
# Patched sgx crates to vendored, uncomment below crate when needed.

# Rust SGX SDK
sgx_alloc         = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_build_helper  = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_cov           = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_libc          = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_rand          = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tcrypto       = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tprotected_fs = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_trts          = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tse           = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tstd          = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
# sgx_tunittest     = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_types         = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_unwind        = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_urts          = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }

# SGX crates
# adler32           = { git = "https://github.com/mesalock-linux/adler32-rs-sgx" }
aho-corasick      = { git = "https://github.com/mesalock-linux/aho-corasick-sgx" }
base64            = { git = "https://github.com/mesalock-linux/rust-base64-sgx" }
byteorder         = { git = "https://github.com/mesalock-linux/byteorder-sgx" }
bytes             = { git = "https://github.com/mesalock-linux/bytes-sgx" }
chrono            = { git = "https://github.com/mesalock-linux/chrono-sgx" }
# color_quant       = { git = "https://github.com/mesalock-linux/color_quant-sgx" }
# crc32fast         = { git = "https://github.com/mesalock-linux/rust-crc32fast-sgx" }
# deflate           = { git = "https://github.com/mesalock-linux/deflate-rs-sgx", branch = "dev" }
gbdt              = { git = "https://github.com/mesalock-linux/gbdt-rs", branch = "mesatee-sgx" }
getrandom         = { git = "https://github.com/mesalock-linux/getrandom-sgx" }
crc               = { git = "https://github.com/mesalock-linux/crc-rs-sgx" }
# gif               = { git = "https://github.com/mesalock-linux/image-gif-sgx" }
image             = { git = "https://github.com/mesalock-linux/image-sgx" }
# inflate           = { git = "https://github.com/mesalock-linux/inflate-sgx" }
itoa              = { git = "https://github.com/mesalock-linux/itoa-sgx" }
# jpeg-decoder      = { git = "https://github.com/mesalock-linux/jpeg-decoder-sgx" }
log               = { git = "https://github.com/mesalock-linux/log-sgx" }
# lzw               = { git = "https://github.com/mesalock-linux/lzw-sgx" }
num-bigint        = { git = "https://github.com/mesalock-linux/num-bigint-sgx" }
num-traits        = { git = "https://github.com/mesalock-linux/num-traits-sgx" }
# parity-wasm       = { git = "https://github.com/mesalock-linux/parity-wasm-sgx" }
percent-encoding  = { git = "https://github.com/mesalock-linux/rust-url-sgx" }
# png               = { git = "https://github.com/mesalock-linux/image-png-sgx" }
profiler_builtins = { git = "https://github.com/mesalock-linux/sgx-fake-profiler-builtins" }
prost             = { git = "https://github.com/mesalock-linux/prost-sgx" }
quick-error       = { git = "https://github.com/mesalock-linux/quick-error-sgx" }
rand              = { git = "https://github.com/mesalock-linux/rand-sgx", tag = "v0.7.3_sgx1.1.3" }
regex             = { git = "https://github.com/mesalock-linux/regex-sgx" }
ring              = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5" }
rustls            = { git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx-client-cert-verifier-patch" }
# rusty-machine     = { git = "https://github.com/mesalock-linux/rusty-machine-sgx" }
sct               = { git = "https://github.com/mesalock-linux/sct.rs", branch = "mesalock_sgx" }
serde             = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_derive      = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json        = { git = "https://github.com/mesalock-linux/serde-json-sgx" }
threadpool        = { git = "https://github.com/mesalock-linux/rust-threadpool-sgx" }
# tiff              = { git = "https://github.com/mesalock-linux/image-tiff-sgx" }
toml              = { git = "https://github.com/mesalock-linux/toml-rs-sgx" }
uuid              = { git = "https://github.com/mesalock-linux/uuid-sgx" }
# wabt              = { git = "https://github.com/mesalock-linux/wabt-rs-sgx", branch = "v0.9-core" }
# wasmi             = { git = "https://github.com/mesalock-linux/wasmi-sgx" }
webpki            = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }
webpki-roots      = { git = "https://github.com/mesalock-linux/webpki-roots", branch = "mesalock_sgx" }
yasna             = { git = "https://github.com/mesalock-linux/yasna.rs-sgx" }
