[package]
name = "teaclave_proto"
version = "0.2.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "RPC protocol of Teaclave services."
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = [
    "sgx_tstd",
    "teaclave_types/mesalock_sgx",
    "teaclave_rpc/mesalock_sgx",
    "teaclave_crypto/mesalock_sgx",
]
cov = ["sgx_cov"]

[dependencies]
anyhow       = { version = "1.0.26" }
base64       = { version = "0.13.0" }
cfg-if       = { version = "0.1.9" }
prost        = { version = "0.6.0" }
rand         = { version = "0.7.0" }
serde        = { version = "1.0.39", features = ["derive"] }
serde_json   = { version = "1.0.39" }
url          = { version = "2.1.1" }
uuid          = { version = "0.8.1", features = ["v4"] }

sgx_cov      = { version = "1.1.3", optional = true }
sgx_tstd     = { version = "1.1.3", features = ["net", "backtrace"], optional = true }
sgx_types    = { version = "1.1.3" }

teaclave_rpc = { path = "../../rpc" }
teaclave_types = { path = "../../types" }
teaclave_crypto = { path = "../../crypto" }
