[package]
name = "teaclave_sgx_tool"
version = "0.2.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave SGX Tool"
license = "Apache-2.0"
build = "build.rs"
edition = "2018"

[dependencies]
log        = { version = "0.4.6", features = ["release_max_level_info"] }
env_logger = { version = "0.7.1" }
anyhow     = { version = "1.0.26" }
serde            = { version = "1.0.92", features = ["derive"] }
serde_json       = { version = "1.0.39" }
raw-cpuid = "8.1.0"
structopt = "0.3"

teaclave_binder            = { path = "../../binder", features = ["app"] }
teaclave_types             = { path = "../../types" }

sgx_types = { version = "1.1.3" }
