[package]
name = "teaclave_client_sdk"
version = "0.2.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave Rust Client SDK"
license = "Apache-2.0"
edition = "2018"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
teaclave_types = { path = "../../types", features = ["app"] }
teaclave_attestation = { path = "../../attestation" }
teaclave_rpc = { path = "../../rpc" }
teaclave_proto = { path = "../../services/proto" }
anyhow       = { version = "1.0.26" }
url          = { version = "2.1.1" }
serde_json    = { version = "1.0.39" }
serde         = { version = "1.0.92" }
pem = "0.7.0"
libc = "0.2.68"

[patch.crates-io]
sgx_types = { path = "../../third_party/rust-sgx-sdk/sgx_types" }