[package]
name = "teaclave_execution_service_enclave"
version = "0.2.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave Execution Service"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "teaclave_execution_service_enclave"
crate-type = ["staticlib", "rlib"]

[features]
default = []
mesalock_sgx = [
  "sgx_tstd",
  "teaclave_attestation/mesalock_sgx",
  "teaclave_proto/mesalock_sgx",
  "teaclave_binder/mesalock_sgx",
  "teaclave_rpc/mesalock_sgx",
  "teaclave_service_enclave_utils/mesalock_sgx",
  "teaclave_types/mesalock_sgx",
  "teaclave_crypto/mesalock_sgx",
  "teaclave_config/mesalock_sgx",
  "teaclave_config/build_config",
  "teaclave_worker/mesalock_sgx",
]
cov = ["teaclave_service_enclave_utils/cov"]
enclave_unit_test = ["teaclave_binder/enclave_unit_test", "teaclave_test_utils/mesalock_sgx"]

[dependencies]
log           = { version = "0.4.6", features = ["release_max_level_info"] }
anyhow        = { version = "1.0.26" }
serde_json    = { version = "1.0.39" }
serde         = { version = "1.0.92", features = ["derive"] }
thiserror     = { version = "1.0.9" }
gbdt          = { version = "0.1.0", features = ["input", "enable_training"] }
uuid          = { version = "0.8.1", features = ["v4"] }
url           = { version = "2.1.1", features = ["serde"]}

teaclave_attestation           = { path = "../../../attestation" }
teaclave_config                = { path = "../../../config" }
teaclave_proto                 = { path = "../../proto" }
teaclave_binder                = { path = "../../../binder" }
teaclave_rpc                   = { path = "../../../rpc" }
teaclave_service_enclave_utils = { path = "../../utils/service_enclave_utils" }
teaclave_types                 = { path = "../../../types" }
teaclave_crypto                = { path = "../../../crypto" }
teaclave_worker                = { path = "../../../worker" }
teaclave_test_utils            = { path = "../../../tests/utils" , optional = true }

sgx_cov       = { version = "1.1.3", optional = true }
sgx_tstd      = { version = "1.1.3", features = ["net", "thread", "backtrace"], optional = true }
sgx_types     = { version = "1.1.3" }
